apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    orgId: 1
    uid: grafana_loki
    url: http://loki.railway.internal:3100
    isDefault: true
    editable: false
    jsonData:
      timeout: 60
      maxLines: 1000
    
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    uid: grafana_prometheus
    url: http://prometheus.railway.internal:9090
    isDefault: false
    editable: false
    jsonData:
      timeInterval: 30s
      queryTimeout: 60s
    
  - name: Tempo
    type: tempo
    access: proxy
    orgId: 1
    uid: grafana_tempo
    url: http://tempo.railway.internal:3200
    isDefault: false
    editable: false
    jsonData:
      timeout: 60
