apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: ${PROMETHEUS_INTERNAL_URL}
    isDefault: true
    jsonData:
      httpMethod: POST
      exemplarTraceIdDestinations:
        - name: traceId
          datasourceUid: tempo
    editable: true

  - name: Loki
    type: loki
    access: proxy
    url: ${LOKI_INTERNAL_URL}
    jsonData:
      maxLines: 1000
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: "traceId=(\\w+)"
          name: TraceId
          url: '$${__value.raw}'
    editable: true

  - name: Tempo
    type: tempo
    access: proxy
    url: ${TEMPO_INTERNAL_URL}
    uid: tempo
    jsonData:
      httpMethod: GET
      tracesToLogs:
        datasourceUid: loki
        tags: ['service', 'environment']
        mappedTags: [{ key: 'service.name', value: 'service' }]
        mapTagNamesEnabled: true
        spanStartTimeShift: '-1h'
        spanEndTimeShift: '1h'
        filterByTraceID: true
        filterBySpanID: false
      tracesToMetrics:
        datasourceUid: prometheus
        tags: [{ key: 'service.name', value: 'service' }]
        queries:
          - name: 'Request Rate'
            query: 'rate(traces_spanmetrics_calls_total{$$__tags}[5m])'
      serviceMap:
        datasourceUid: prometheus
      nodeGraph:
        enabled: true
    editable: true
