# Imagem fixa: no Railway, a env VERSION=latest sobrescreve ARG e puxava :latest (comportamento diferente do template Mykal).
FROM grafana/grafana-oss:11.5.2

COPY provisioning/datasources /etc/grafana/provisioning/datasources
COPY provisioning/dashboards /etc/grafana/provisioning/dashboards
COPY dashboards /var/lib/grafana/dashboards
